use din_patch::NodeKind;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NodeRegistryEntry {
    pub kind: NodeKind,
    pub module_name: &'static str,
    pub struct_name: &'static str,
    pub react_component: &'static str,
    pub playground_node: &'static str,
    pub alias_note: Option<&'static str>,
}

pub const NODE_REGISTRY: &[NodeRegistryEntry] = &[
    entry(NodeKind::Osc, "osc", "OscNode", "Osc", "OscNode", None),
    entry(NodeKind::Gain, "gain", "GainNode", "Gain", "GainNode", None),
    entry(
        NodeKind::Filter,
        "filter",
        "FilterNode",
        "Filter",
        "FilterNode",
        None,
    ),
    entry(
        NodeKind::Delay,
        "delay",
        "DelayNode",
        "Delay",
        "DelayNode",
        None,
    ),
    entry(
        NodeKind::Reverb,
        "reverb",
        "ReverbNode",
        "Reverb",
        "ReverbNode",
        None,
    ),
    entry(
        NodeKind::Compressor,
        "compressor",
        "CompressorNode",
        "Compressor",
        "CompressorNode",
        None,
    ),
    entry(
        NodeKind::Phaser,
        "phaser",
        "PhaserNode",
        "Phaser",
        "PhaserNode",
        None,
    ),
    entry(
        NodeKind::Flanger,
        "flanger",
        "FlangerNode",
        "Flanger",
        "FlangerNode",
        None,
    ),
    entry(
        NodeKind::Tremolo,
        "tremolo",
        "TremoloNode",
        "Tremolo",
        "TremoloNode",
        None,
    ),
    entry(NodeKind::Eq3, "eq3", "Eq3Node", "EQ3", "EQ3Node", None),
    entry(
        NodeKind::Distortion,
        "distortion",
        "DistortionNode",
        "Distortion",
        "DistortionNode",
        None,
    ),
    entry(
        NodeKind::Chorus,
        "chorus",
        "ChorusNode",
        "Chorus",
        "ChorusNode",
        None,
    ),
    entry(
        NodeKind::NoiseBurst,
        "noise_burst",
        "NoiseBurstNode",
        "NoiseBurst",
        "NoiseBurstNode",
        None,
    ),
    entry(
        NodeKind::WaveShaper,
        "wave_shaper",
        "WaveShaperNode",
        "WaveShaper",
        "WaveShaperNode",
        Some("react-din may render PresetWaveShaper when preset data is present"),
    ),
    entry(
        NodeKind::Convolver,
        "convolver",
        "ConvolverNode",
        "Convolver",
        "ConvolverNode",
        None,
    ),
    entry(
        NodeKind::Analyzer,
        "analyzer",
        "AnalyzerNode",
        "Analyzer",
        "AnalyzerNode",
        None,
    ),
    entry(
        NodeKind::Panner3d,
        "panner_3d",
        "Panner3dNode",
        "Panner",
        "Panner3DNode",
        Some("canonical patch type panner3d maps to the React Panner component"),
    ),
    entry(
        NodeKind::Panner,
        "panner",
        "PannerNode",
        "StereoPanner",
        "StereoPannerNode",
        Some("canonical patch type panner maps to the React StereoPanner component"),
    ),
    entry(
        NodeKind::Mixer,
        "mixer",
        "MixerNode",
        "Gain",
        "MixerNode",
        Some("canonical patch type mixer currently resolves to Gain semantics"),
    ),
    entry(
        NodeKind::AuxSend,
        "aux_send",
        "AuxSendNode",
        "AuxSend",
        "AuxSendNode",
        None,
    ),
    entry(
        NodeKind::AuxReturn,
        "aux_return",
        "AuxReturnNode",
        "AuxReturn",
        "AuxReturnNode",
        None,
    ),
    entry(
        NodeKind::MatrixMixer,
        "matrix_mixer",
        "MatrixMixerNode",
        "MatrixMixer",
        "MatrixMixerNode",
        None,
    ),
    entry(
        NodeKind::Noise,
        "noise",
        "NoiseNode",
        "Noise",
        "NoiseNode",
        None,
    ),
    entry(
        NodeKind::ConstantSource,
        "constant_source",
        "ConstantSourceNode",
        "ConstantSource",
        "ConstantSourceNode",
        None,
    ),
    entry(
        NodeKind::MediaStream,
        "media_stream",
        "MediaStreamNode",
        "MediaStream",
        "MediaStreamNode",
        None,
    ),
    entry(
        NodeKind::Sampler,
        "sampler",
        "SamplerNode",
        "Sampler",
        "SamplerNode",
        Some("react-din may render TriggeredSampler when a trigger handle is wired"),
    ),
    entry(
        NodeKind::Output,
        "output",
        "OutputNode",
        "Gain",
        "OutputNode",
        Some("canonical patch type output currently resolves to Gain semantics"),
    ),
    entry(
        NodeKind::Math,
        "math",
        "MathNode",
        "math()",
        "MathNode",
        None,
    ),
    entry(
        NodeKind::Compare,
        "compare",
        "CompareNode",
        "compare()",
        "CompareNode",
        None,
    ),
    entry(NodeKind::Mix, "mix", "MixNode", "mix()", "MixNode", None),
    entry(
        NodeKind::Clamp,
        "clamp",
        "ClampNode",
        "clamp()",
        "ClampNode",
        None,
    ),
    entry(
        NodeKind::Switch,
        "switch",
        "SwitchNode",
        "switchValue()",
        "SwitchNode",
        None,
    ),
    entry(
        NodeKind::Input,
        "input",
        "InputNode",
        "Input",
        "InputNode",
        None,
    ),
    entry(
        NodeKind::UiTokens,
        "ui_tokens",
        "UiTokensNode",
        "UiTokens",
        "UiTokensNode",
        None,
    ),
    entry(NodeKind::Note, "note", "NoteNode", "Note", "NoteNode", None),
    entry(
        NodeKind::Transport,
        "transport",
        "TransportNode",
        "TransportProvider",
        "TransportNode",
        None,
    ),
    entry(
        NodeKind::StepSequencer,
        "step_sequencer",
        "StepSequencerNode",
        "Sequencer",
        "StepSequencerNode",
        None,
    ),
    entry(
        NodeKind::PianoRoll,
        "piano_roll",
        "PianoRollNode",
        "Track",
        "PianoRollNode",
        None,
    ),
    entry(
        NodeKind::EventTrigger,
        "event_trigger",
        "EventTriggerNode",
        "EventTrigger",
        "EventTriggerNode",
        None,
    ),
    entry(NodeKind::Lfo, "lfo", "LfoNode", "LFO", "LFONode", None),
    entry(
        NodeKind::Voice,
        "voice",
        "VoiceNode",
        "Voice",
        "VoiceNode",
        None,
    ),
    entry(NodeKind::Adsr, "adsr", "AdsrNode", "ADSR", "ADSRNode", None),
    entry(
        NodeKind::MidiNote,
        "midi_note",
        "MidiNoteNode",
        "MidiNoteInput",
        "MidiNoteNode",
        None,
    ),
    entry(
        NodeKind::MidiCc,
        "midi_cc",
        "MidiCcNode",
        "MidiCCInput",
        "MidiCCNode",
        None,
    ),
    entry(
        NodeKind::MidiNoteOutput,
        "midi_note_output",
        "MidiNoteOutputNode",
        "MidiNoteOutput",
        "MidiNoteOutputNode",
        None,
    ),
    entry(
        NodeKind::MidiCcOutput,
        "midi_cc_output",
        "MidiCcOutputNode",
        "MidiCCOutput",
        "MidiCCOutputNode",
        None,
    ),
    entry(
        NodeKind::MidiSync,
        "midi_sync",
        "MidiSyncNode",
        "MidiTransportSync",
        "MidiSyncNode",
        None,
    ),
    entry(
        NodeKind::MidiPlayer,
        "midi_player",
        "MidiPlayerNode",
        "MidiPlayer",
        "MidiPlayerNode",
        None,
    ),
];

pub fn node_registry() -> &'static [NodeRegistryEntry] {
    NODE_REGISTRY
}

pub fn registry_entry(kind: NodeKind) -> Option<&'static NodeRegistryEntry> {
    NODE_REGISTRY.iter().find(|entry| entry.kind == kind)
}

pub fn registry_has_all_node_kinds() -> bool {
    NodeKind::ALL
        .iter()
        .all(|kind| registry_entry(*kind).is_some())
        && NODE_REGISTRY.len() == NodeKind::ALL.len()
}

const fn entry(
    kind: NodeKind,
    module_name: &'static str,
    struct_name: &'static str,
    react_component: &'static str,
    playground_node: &'static str,
    alias_note: Option<&'static str>,
) -> NodeRegistryEntry {
    NodeRegistryEntry {
        kind,
        module_name,
        struct_name,
        react_component,
        playground_node,
        alias_note,
    }
}
